version: "3.9"

services:
  # Django backend service
  backend:
    build:
      context: ./mynotes
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mynotes:/app
    environment:
      - DEBUG=1

  # React frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./frontend:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.config:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
